name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libffi-dev libssl-dev
        pip install --upgrade pip
        pip install cython==0.29.33 buildozer

    - name: Install Android SDK cmdline tools
      run: |
        mkdir -p "$HOME/android-sdk/cmdline-tools"
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o sdk.zip
        unzip -q sdk.zip
        mv cmdline-tools "$HOME/android-sdk/cmdline-tools/latest"
        rm sdk.zip

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Install build-tools 30.0.3
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3"

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
